url_copier_enabled:
  default: true
  client: true
url_copier_domain:
  default: "replace_with_this_domain.com"
  client: true
url_copier_append:
  default: "?param_key1=param_value1"
  client: true
url_copier_categories:
  type: list
  list_type: compact
  default: "support|feature-requests|secret-stuff"
  client: true
