plugins:
  url_copier_replace_hostname:
    default: "replace-with-this-domain.com"
    client: true
    description: "Hostname to replace with"
  url_copier_append_string:
    default: "?extra=param"
    client: true
    description: "String to append to the URL"
  url_copier_categories:
    default: "support,announcements"
    client: true
    description: "Comma-separated list of category slugs"
